version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: stima
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/backend/database/stima.sql:/docker-entrypoint-initdb.d/stima.sql
volumes:
  mysql-data:
